{{- range $.Values.issuers }}
  {{- if .create }}
    {{- if or (and (.ovhAuthentication) (.ovhAuthenticationRef)) (and (not .ovhAuthentication) (not .ovhAuthenticationRef)) }}
      {{ fail "Error: For each issuer you wish to create, you need to define either 'ovhAuthentication' or 'ovhAuthenticationRef'" }}
    {{- end }}
    {{- if eq (include "cert-manager-webhook-ovh.isOvhAuthenticationAvail" .ovhAuthentication) "true" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-ovh-credentials" .name }}
  {{- if eq .kind "Issuer" }}
  namespace: {{ .namespace | quote }}
  {{- else }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- end }}
  labels:
    {{- include "cert-manager-webhook-ovh.labels" $ | nindent 4 }}
data:
  applicationKey: {{ .ovhAuthentication.applicationKey | b64enc | quote }}
  applicationSecret: {{ .ovhAuthentication.applicationSecret | b64enc | quote }}
  consumerKey: {{ .ovhAuthentication.consumerKey | b64enc | quote }}
---
    {{- end }}{{/* end if eq (include "cert..." */}}
  {{- end }}{{/* end if .create */}}
{{- end }}{{/* end range */}}